services:
  marlin-search-indexer:
    image: ghcr.io/l33tlamer/marlin-search:latest
    container_name: marlin-search-indexer
    networks:
      - marlin-network
    ports:
      - "5000:5000"
    depends_on:
      marlin-search-meilisearch:
        condition: service_healthy
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - MEILISEARCH_URL=http://marlin-search-meilisearch:7700
      - MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY}
      - EXPRESS_AUTH_TOKEN=${EXPRESS_AUTH_TOKEN}
      - SCRAPE_INTERVAL_MINUTES=${SCRAPE_INTERVAL_MINUTES}
      - BATCH_SIZE=${BATCH_SIZE}
      - NODE_ENV=production

  marlin-search-meilisearch:
    image: getmeili/meilisearch:v1.34
    container_name: marlin-search-meilisearch
    networks:
      - marlin-network
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY}
      - MEILI_ENV=production
    volumes:
      - meili_data:/meili_data
    healthcheck:
       test: curl --fail -s http://localhost:7700/health | grep -Eo '\"status\":\"available\"' || exit 1

volumes:
  meili_data:
networks:
  marlin-network:
